name: 100ui
favicon: null
layout_spectrum: 0.21533
typography_spectrum: 0.39012
title: 100 days of ui
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#864aee'
    - '#ffffff'
    - '#b39aea'
    - '#e4dcf8'
    - '#cdb5f8'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
